version: "3.9"
services:
  moreronn_web:
    build: .
    ports:
      - "9090:9090"
    command: "uwsgi --http :9090 --wsgi-file web/moreronn.wsgi --master --processes 1 --threads 2" 
      #network_mode: "host"
